version: '3.5'

services:
  goarni:
    container_name: gorani
    image: gorani:prod
    volumes:
      - ../src:/home/gorani
      - ./configs/nginx:/etc/nginx/conf.d
    environment:
      - WEBRTC_ADDRESS=${WEBRTC_ADDRESS}
    entrypoint: "/entrypoint.sh"
    ports:
      - 80:80
      - 443:443
